### ISSUE TITLE
Tony Robbins site requires a valid email

### ISSUE THREAD

**Issue by oferrigni** [thesarahhagan/DevOps-Days#1]
You can no longer get the free DISC assessment without a valid email (requires login).

**Comment by thesarahhagan** [comment]
Thanks @oferrigni--**_boo_**, but also kind of hoping my tiny github ReadMe was sending them so many people that they decided to lock it down. I added this note on the ReadMe.

**Comment by oferrigni** [comment]
My pleasure! Thanks for posting the resources!
